name: CD - Deploy to Kind or Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ma-cav/devops-libs/.github/workflows/stages/docker/docker.deploy.yml@main
    with:
      image: ghcr.io/myorg/service-a:${{ github.run_number }}
      namespace: app
      manifests_path: manifests/
      cluster_type: kind # ou "generic" para usar kubeconfig
      # kubeconfig: ${{ secrets.KUBECONFIG_B64 }} # se cluster_type=generic
    type: reuseable