name: CD - Deploy to Kind or Kubernetes

on:
  # Dispara manualmente
  workflow_dispatch:
  # Dispara automaticamente para PRs para main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    uses: ma-cav/devops-libs/.github/workflows/stages/docker/docker.deploy.yml@main
    with:
      # Aqui você pode buscar automaticamente a última tag do CI
      image: mcavalcanti/dotnet-sample:${{ github.run_number }}
      namespace: ${{ vars.NAMESPACE }}
      manifests_path: manifests/
      cluster_type: kind
 
      